sudo: required
services:
  - docker

before_install:
  - docker build -t ammarkureja/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ammarkureja/react-test npm test -- --coverage

after_success: 
 - docker build -t ammarkureja/multi-client ./client
 - docker build -t ammarkureja/multi-nginx ./nginx
 - docker build -t ammarkureja/multi-server ./server
 - docker build -t ammarkureja/multi-worker ./worker
# login to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
 - docker push ammarkureja/multi-client
 - docker push ammarkureja/multi-nginx
 - docker push ammarkureja/multi-server
 - docker push ammarkureja/multi-worker


deploy: 
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-017425166832
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY